name: "Publish library to GitHub Packages"
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        env:
          USERNAME: SorrowBlue
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew binding-ktx:publish

      - name: Publish
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # リリースのタグ (必須)
          tag_name: ${{ github.ref }}
          # リリースのタイトル (必須)
          release_name: ${{ github.ref }}
          # リリースのタイトル (省略可能)
          body: |
            # Android Jetpack Ktx
          # 下書き状態で作成する場合は true (省略時 false)
          draft: true
          # プレリリース表示を付ける場合は true (省略時 false)
          prerelease: true
